import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import "@/app/globals.css";
import { Navbar } from "@/components/navbar";
import localFont from "next/font/local";
import { AlertProvider } from "@/components/alert-context";

const sfDisplay = localFont({
  src: [
    {
      path: "../public/fonts/SFNSDisplay-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/SFNSDisplay-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/SFNSDisplay-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Exor - Tech Innovations",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sfDisplay.className} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AlertProvider>
            <Navbar />
            {children}
          </AlertProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
